window.Quiz = window.Quiz || {};

Quiz.themes = {
  exodus: {
    id: "exodus",
    name: "Exodus",
    backgroundImage: "backgrounds/exodus.png",
    colors: {
      primary: "#c0392b",
      secondary: "#2c3e50",
      accent: "#f39c12",
      background: "#fdf6e3",
      tileBack: "#8e44ad",
      tileFront: "#ecf0f1",
      team1: "#e74c3c",
      team2: "#3498db",
    },
    labels: {
      points: ["Manna", "Quail from Heaven", "Water from the Rock", "Pillar of Fire", "Cloud by Day", "Grapes of Eshcol", "Tablets of Stone", "Jars of Oil"],
      steal: ["Plundering Egypt", "The Ten Plagues", "Spoils of War"],
      bonusTurn: ["Moses' Staff", "Pillar of Cloud", "Caleb's Courage"],
      jackpot: ["Land of Milk and Honey", "Entering the Promised Land"],
      loseTurn: "40 Years Wandering",
      double: "Parting the Red Sea",
      negative: ["Golden Calf", "Pharaoh's Army"],
      bank: "Set Up Camp",
      risk: "Journey On",
      swap: ["Tables Turned", "Red Sea Moment"],
      mystery: ["Burning Bush", "The Twelve Spies", "What's Behind the Cloud?", "Rahab's Secret"],
      tithe: ["Pharaoh's Tax", "Egyptian Tribute"],
      earthquake: "Korah's Rebellion",
      gift: ["Sharing the Manna", "A Generous Spirit", "Jethro's Kindness"],
    },
    icons: {
      points: ["\u{1F35E}", "\u{1F983}", "\u{1F4A7}", "\u{1F525}", "\u{2601}\uFE0F", "\u{1F347}", "\u{1F4DC}", "\u{1F3FA}"],
      steal: ["\u{1F4B0}", "\u{1F41B}", "\u{2694}\uFE0F"],
      bonusTurn: ["\u{1F525}", "\u{2601}\uFE0F", "\u{1F4AA}"],
      jackpot: "\u{1F3D4}\uFE0F",
      loseTurn: "\u{1F3DC}\uFE0F",
      double: "\u{1F30A}",
      negative: ["\u{1F402}", "\u{2694}\uFE0F"],
      bank: "\u26FA",
      risk: "\u{1F9ED}",
      swap: ["\u{1F504}", "\u{1F30A}"],
      mystery: ["\u{2753}", "\u{1F50D}", "\u{2601}\uFE0F", "\u{1F3E0}"],
      tithe: ["\u{1F4DC}", "\u{1F4B0}"],
      earthquake: "\u{1F30B}",
      gift: ["\u{1F54A}\uFE0F", "\u{1F91D}", "\u{2615}"],
    },
    ladderSteps: [
      "Leave Egypt",
      "Cross Red Sea",
      "Desert of Sin",
      "Mount Sinai",
      "Promised Land",
    ],
    auctionLabels: {
      treasure: "Ark of Gold",
      cursed: "Golden Calf",
      steal: "Plunder",
      jackpot: "Pharaoh's Treasure",
      bid: "Offering",
    },
    auctionIcons: {
      treasure: "\u{1F3FA}",
      cursed: "\u{1F402}",
      steal: "\u{1F4B0}",
      jackpot: "\u{1F451}",
      bid: "\u{1F4B0}",
    },
    bombLabels: {
      boom: "Pharaoh's Trap",
      bonus: "Safe Passage",
      defused: "Spared!",
      points: "Blessing",
    },
    bombIcons: {
      boom: "\u{1F4A5}",
      bonus: "\u{1F6E1}\uFE0F",
      defused: "\u{1F54A}\uFE0F",
      points: "\u{1F4BF}",
    },
    mapPaths: ["Nile Delta", "Sinai Wilderness", "Oasis of Elim", "Mount Nebo"],
    mapLabels: {
      deadEnd: "Lost in Desert",
      hazard: "Sandstorm",
      treasure: "Hidden Oasis",
      reward: "Discovery",
    },
    mapIcons: {
      deadEnd: "\u{1F3DC}\uFE0F",
      hazard: "\u{1F32A}\uFE0F",
      treasure: "\u{1F3FA}",
      reward: "\u{1F4BF}",
    },
    tugRoundNames: ["Warm-Up", "The Struggle", "Final Showdown"],
    tugLabels: {
      pull: "Pull!",
      superPull: "Mighty Pull!",
      slip: "Stumble",
      anchor: "Rooted",
    },
    tugIcons: {
      pull: "\u{1F4AA}",
      superPull: "\u26A1",
      slip: "\u{1F4A6}",
      anchor: "\u{1F6E1}\uFE0F",
    },
  },

  christmas: {
    id: "christmas",
    name: "Christmas",
    backgroundImage: "backgrounds/christmas.png",
    colors: {
      primary: "#c0392b",
      secondary: "#27ae60",
      accent: "#f1c40f",
      background: "#fefefe",
      tileBack: "#27ae60",
      tileFront: "#fff8e7",
      team1: "#e74c3c",
      team2: "#2ecc71",
    },
    labels: {
      points: "Present",
      steal: "Grinch",
      bonusTurn: "Snow Globe",
      jackpot: "Christmas Miracle",
      loseTurn: "Snowstorm",
      double: "Stocking Stuffer",
      negative: "Lump of Coal",
      bank: "Wrap It Up",
      risk: "Open Another",
      swap: "Secret Santa",
      mystery: "Mystery Gift",
      tithe: "Elf Tax",
      earthquake: "Avalanche",
      gift: "Charity",
    },
    icons: {
      points: "\u{1F381}",
      steal: "\u{1F9B9}",
      bonusTurn: "\u2B50",
      jackpot: "\u{1F384}",
      loseTurn: "\u{1F328}\uFE0F",
      double: "\u{1F9E6}",
      negative: "\u{1FAA8}",
      bank: "\u{1F380}",
      risk: "\u{1F381}",
      swap: "\u{1F385}",
      mystery: "\u{1F381}",
      tithe: "\u{1F9DD}",
      earthquake: "\u{1F328}\uFE0F",
      gift: "\u{1F49D}",
    },
    ladderSteps: [
      "Advent Begins",
      "Christmas Eve",
      "The Stable",
      "The Manger",
      "Christmas Morning!",
    ],
    auctionLabels: {
      treasure: "Mystery Gift",
      cursed: "Empty Box",
      steal: "Stocking Raid",
      jackpot: "Toy Chest",
      bid: "Wishlist",
    },
    auctionIcons: {
      treasure: "\u{1F381}",
      cursed: "\u{1F4E6}",
      steal: "\u{1F9E6}",
      jackpot: "\u{1F385}",
      bid: "\u{1F4DC}",
    },
    bombLabels: {
      boom: "Firecracker!",
      bonus: "Extra Tinsel",
      defused: "Safe!",
      points: "Treat",
    },
    bombIcons: {
      boom: "\u{1F9E8}",
      bonus: "\u2744\uFE0F",
      defused: "\u2744\uFE0F",
      points: "\u{1F36C}",
    },
    mapPaths: ["Village Square", "Snowy Forest", "Mountain Pass", "Santa's Workshop"],
    mapLabels: {
      deadEnd: "Snowed In",
      hazard: "Icy Path",
      treasure: "Santa's Grotto",
      reward: "Gift Found",
    },
    mapIcons: {
      deadEnd: "\u26C4",
      hazard: "\u{1F9CA}",
      treasure: "\u{1F385}",
      reward: "\u{1F381}",
    },
    tugRoundNames: ["Friendly Tug", "Snowball Fight", "The Big Pull"],
    tugLabels: {
      pull: "Heave!",
      superPull: "Reindeer Power!",
      slip: "Slipped on Ice",
      anchor: "Frozen Solid",
    },
    tugIcons: {
      pull: "\u{1F4AA}",
      superPull: "\u{1F98C}",
      slip: "\u{1F9CA}",
      anchor: "\u2744\uFE0F",
    },
  },
};
