window.Quiz = window.Quiz || {};

Quiz.themes = {
  exodus: {
    id: "exodus",
    name: "Exodus",
    backgroundImage: "backgrounds/exodus.png",
    colors: {
      primary: "#c0392b",
      secondary: "#2c3e50",
      accent: "#f39c12",
      background: "#fdf6e3",
      tileBack: "#8e44ad",
      tileFront: "#ecf0f1",
      team1: "#e74c3c",
      team2: "#3498db",
    },
    labels: {
      points: "Manna",
      steal: "Plague",
      bonusTurn: "Burning Bush",
      jackpot: "Promised Land",
      loseTurn: "Wilderness",
      double: "Parting the Sea",
      negative: "Pharaoh's Curse",
      bank: "Set Up Camp",
      risk: "Journey On",
    },
    icons: {
      points: "\u{1F35E}",
      steal: "\u{1F41B}",
      bonusTurn: "\u{1F525}",
      jackpot: "\u{1F3D4}\uFE0F",
      loseTurn: "\u{1F3DC}\uFE0F",
      double: "\u{1F30A}",
      negative: "\u{1F40D}",
      bank: "\u26FA",
      risk: "\u{1F9ED}",
    },
    ladderSteps: [
      "Leave Egypt",
      "Cross Red Sea",
      "Desert of Sin",
      "Mount Sinai",
      "Promised Land",
    ],
  },

  christmas: {
    id: "christmas",
    name: "Christmas",
    backgroundImage: "backgrounds/christmas.png",
    colors: {
      primary: "#c0392b",
      secondary: "#27ae60",
      accent: "#f1c40f",
      background: "#fefefe",
      tileBack: "#27ae60",
      tileFront: "#fff8e7",
      team1: "#e74c3c",
      team2: "#2ecc71",
    },
    labels: {
      points: "Present",
      steal: "Grinch",
      bonusTurn: "Star of Bethlehem",
      jackpot: "Christmas Miracle",
      loseTurn: "Snowstorm",
      double: "Stocking Stuffer",
      negative: "Lump of Coal",
      bank: "Wrap It Up",
      risk: "Open Another",
    },
    icons: {
      points: "\u{1F381}",
      steal: "\u{1F9B9}",
      bonusTurn: "\u2B50",
      jackpot: "\u{1F384}",
      loseTurn: "\u{1F328}\uFE0F",
      double: "\u{1F9E6}",
      negative: "\u{1FAA8}",
      bank: "\u{1F380}",
      risk: "\u{1F381}",
    },
    ladderSteps: [
      "Advent Begins",
      "Christmas Eve",
      "The Stable",
      "The Manger",
      "Glory to God!",
    ],
  },
};
